# Hotel Booking Demand Analysis
## Feature Engineering
* **Goal:** Filling missing values and preparing Dateset for ML

In [25]:
# Import libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

file_path = 'hotel_bookings.csv'

# Safe data loading with try/except
try:
    df = pd.read_csv(file_path)
    print('Load successfully')
except FileNotFoundError:
    print('File not Found, check {file_path}')

Load successfully

In [26]:
# First inspection of the dataset
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [27]:
# Statistic metrix of dataset
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [28]:
# Checking the shape
print(f'Rows: {df.shape[0]} -- Columns: {df.shape[1]}')

Rows: 119390 -- Columns: 32

In [29]:
# Checking on missing values
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [30]:
print(df['children'].isna())

0         False
1         False
2         False
3         False
4         False
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Name: children, Length: 119390, dtype: bool

In [31]:
# Checking the missing values in the column child - which hotel 
print(df[df['children'].isna()])

            hotel  is_canceled  lead_time  arrival_date_year  \
40600  City Hotel            1          2               2015
40667  City Hotel            1          1               2015
40679  City Hotel            1          1               2015
41160  City Hotel            1          8               2015

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
40600             August                        32                          3
40667             August                        32                          5
40679             August                        32                          5
41160             August                        33                         13

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
40600                        1                     0       2  ...
40667                        0                     2       2  ...
40679                        0                     2       3  ...
41160                        2                     5       2  ...

       deposit_type  agent company days_in_waiting_list    customer_type  \
40600    No Deposit    NaN     NaN                    0  Transient-Party
40667    No Deposit   14.0     NaN                    0  Transient-Party
40679    No Deposit    NaN     NaN                    0  Transient-Party
41160    No Deposit    9.0     NaN                    0  Transient-Party

        adr  required_car_parking_spaces  total_of_special_requests  \
40600  12.0                            0                          1
40667  12.0                            0                          1
40679  18.0                            0                          2
41160  76.5                            0                          1

       reservation_status reservation_status_date
40600            Canceled              2015-08-01
40667            Canceled              2015-08-04
40679            Canceled              2015-08-04
41160            Canceled              2015-08-09

[4 rows x 32 columns]

**Note on Missing Values (Children):**
The analysis revealed 4 missing records in the `children` column, all originating from the City Hotel segment. To handle these missing values without distorting the distribution, the median number of children for the City Hotel will be calculated and utilized to impute the empty entries.

In [32]:
# Creating variable for city hotel and childrens mode
mode_child_city = df[df['hotel'] == 'City Hotel']['children'].mode()[0]

# Filling the missing values with the 
df['children'] = df['children'].fillna(mode_child_city)

# Checking on missing values again
print(df.isna().sum())

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               0
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [44]:
# Checking the unique values for column 'agent'
print(df['agent'].unique())

[ nan 304. 240. 303.  15. 241.   8. 250. 115.   5. 175. 134. 156. 243.
 242.   3. 105.  40. 147. 306. 184.  96.   2. 127.  95. 146.   9. 177.
   6. 143. 244. 149. 167. 300. 171. 305.  67. 196. 152. 142. 261. 104.
  36.  26.  29. 258. 110.  71. 181.  88. 251. 275.  69. 248. 208. 256.
 314. 126. 281. 273. 253. 185. 330. 334. 328. 326. 321. 324. 313.  38.
 155.  68. 335. 308. 332.  94. 348. 310. 339. 375.  66. 327. 387. 298.
  91. 245. 385. 257. 393. 168. 405. 249. 315.  75. 128. 307.  11. 436.
   1. 201. 183. 223. 368. 336. 291. 464. 411. 481.  10. 154. 468. 410.
 390. 440. 495. 492. 493. 434.  57. 531. 420. 483. 526. 472. 429.  16.
 446.  34.  78. 139. 252. 270.  47. 114. 301. 193. 182. 135. 350. 195.
 352. 355. 159. 363. 384. 360. 331. 367.  64. 406. 163. 414. 333. 427.
 431. 430. 426. 438. 433. 418. 441. 282. 432.  72. 450. 180. 454. 455.
  59. 451. 254. 358. 469. 165. 467. 510. 337. 476. 502. 527. 479. 508.
 535. 302. 497. 187.  13.   7.  27.  14.  22.  17.  28.  42.  20.  19.
  45.  37.  61.  39.  21.  24.  41.  50.  30.  54.  52.  12.  44.  31.
  83.  32.  63.  60.  55.  56.  89.  87. 118.  86.  85. 210. 214. 129.
 179. 138. 174. 170. 153.  93. 151. 119.  35. 173.  58.  53. 133.  79.
 235. 192. 191. 236. 162. 215. 157. 287. 132. 234.  98.  77. 103. 107.
 262. 220. 121. 205. 378.  23. 296. 290. 229.  33. 286. 276. 425. 484.
 323. 403. 219. 394. 509. 111. 423.   4.  70.  82.  81.  74.  92.  99.
  90. 112. 117. 106. 148. 158. 144. 211. 213. 216. 232. 150. 267. 227.
 247. 278. 280. 285. 289. 269. 295. 265. 288. 122. 294. 325. 341. 344.
 346. 359. 283. 364. 370. 371.  25. 141. 391. 397. 416. 404. 299. 197.
  73. 354. 444. 408. 461. 388. 453. 459. 474. 475. 480. 449.]

In [45]:
# Checking the unique values for column 'company'
print(df['company'].unique())

[ nan 110. 113. 270. 178. 240. 154. 144. 307. 268.  59. 204. 312. 318.
  94. 174. 274. 195. 223. 317. 281. 118.  53. 286.  12.  47. 324. 342.
 373. 371. 383.  86.  82. 218.  88.  31. 397. 392. 405. 331. 367.  20.
  83. 416.  51. 395. 102.  34.  84. 360. 394. 457. 382. 461. 478. 386.
 112. 486. 421.   9. 308. 135. 224. 504. 269. 356. 498. 390. 513. 203.
 263. 477. 521. 169. 515. 445. 337. 251. 428. 292. 388. 130. 250. 355.
 254. 543. 531. 528.  62. 120.  42.  81. 116. 530. 103.  39.  16.  92.
  61. 501. 165. 291. 290.  43. 325. 192. 108. 200. 465. 287. 297. 490.
 482. 207. 282. 437. 225. 329. 272.  28.  77. 338.  72. 246. 319. 146.
 159. 380. 323. 511. 407. 278.  80. 403. 399.  14. 137. 343. 346. 347.
 349. 289. 351. 353.  54.  99. 358. 361. 362. 366. 372. 365. 277. 109.
 377. 379.  22. 378. 330. 364. 401. 232. 255. 384. 167. 212. 514. 391.
 400. 376. 402. 396. 302. 398.   6. 370. 369. 409. 168. 104. 408. 413.
 148.  10. 333. 419. 415. 424. 425. 423. 422. 435. 439. 442. 448. 443.
 454. 444.  52. 459. 458. 456. 460. 447. 470. 466. 484. 184. 485.  32.
 487. 491. 494. 193. 516. 496. 499.  29.  78. 520. 507. 506. 512. 126.
  64. 242. 518. 523. 539. 534. 436. 525. 541.  40. 455. 410.  45.  38.
  49.  48.  67.  68.  65.  91.  37.   8. 179. 209. 219. 221. 227. 153.
 186. 253. 202. 216. 275. 233. 280. 309. 321.  93. 316.  85. 107. 350.
 279. 334. 348. 150.  73. 385. 418. 197. 450. 452. 115.  46.  76.  96.
 100. 105. 101. 122.  11. 139. 142. 127. 143. 140. 149. 163. 160. 180.
 238. 183. 222. 185. 217. 215. 213. 237. 230. 234.  35. 245. 158. 258.
 259. 260. 411. 257. 271.  18. 106. 210. 273.  71. 284. 301. 305. 293.
 264. 311. 304. 313. 288. 320. 314. 332. 341. 352. 243. 368. 393. 132.
 220. 412. 420. 426. 417. 429. 433. 446. 357. 479. 483. 489. 229. 481.
 497. 451. 492.]

In [47]:
# Checking if 0 represents a agent or company aswell
print(df[df['company']<1])
print(df[df['agent']<1])

Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date]
Index: []

[0 rows x 32 columns]
Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date]
Index: []

[0 rows x 32 columns]

**Note:** The missing values in both columns 'agent' and 'company' are not strings, they are numbers, which indicates the number represents a special agent in both hotels starting with 1. If I am using unknown, the columns will be converted into strings. Therefore I decided to fill the missing values with a 0. After checking both columns for the unique values it shows, that only integers in the columns

In [51]:
# Filling missing values in 'agent' and 'company' with 0. These likely represent individual leisure guests who booked directly without an agent or corporate contract.
df['agent'] = df['agent'].fillna(0)
df['company'] = df['company'].fillna(0)

# Check for missing values
print(df.isna().sum())

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            0
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
agent                               0
company                             0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
dtype: int64

In [52]:
# Filling missing 'country' values will UNK for unknown
df['country'] = df['country'].fillna('UNK')

# Checking for missing values
print(df.isna().sum())

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

**Note:** All missig values are filled.