# Hotel Booking Demand Analysis
## Feature Engineering
## 2nd Iteration
* **Goal:** Filling missing values and preparing Dataset for ML with the saved seperated datasets from 01b_Hotel_Booking_EDA_V2

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns

# Safe dataloading for both datasets
file_with_dup = 'hotel_booking_with_dup.csv'
file_no_dup = 'hotel_booking_no_dup.csv'
try:
    df_with_dup = pd.read_csv(file_with_dup)
    print(f'File: {file_with_dup} load successfully')
except FileNotFoundError:
    print(f'File not found - {file_with_dup}')
try:
    df_no_dup = pd.read_csv(file_no_dup)
    print(f'File: {file_no_dup} load successfully')
except FileNotFoundError:
    print(f'File not found - {file_no_dup}')

File: hotel_booking_with_dup.csv load successfully
File: hotel_booking_no_dup.csv load successfully

**Note:** As the working process is now with two datasets, I will start implementing functions to reduce typing errors.

In [4]:
# Starting with the general inspection for both datasets and implement a function to reduce error

def data_inspection(df, name):
    """
    Inspection function to safely analyze dataset structures,
    missing values, and data types without code duplication
    """
    print("=" * 60)
    print(f'Dataset inspection for: {name}')
    print("=" * 60)
    print('Dataset Shape:')
    print(f'Rows: {df.shape[0]} -- Columns {df.shape[1]}')
    print('\n')
    print('Missing Values')
    missing = df.isna().sum()
    print(missing[missing > 0] if missing.sum() > 0 else 'No Missing Values found')
    print('\n')
    print('Datatypes & Info:')
    df.info()
    print('\n')
    print('Header & First Rows')
    display(df.head())

In [5]:
# Check the datasest without duplicates with function
data_inspection(df_no_dup, 'Dataset without Duplicates')

============================================================
Dataset inspection for: Dataset without Duplicates
============================================================
Dataset Shape:
Rows: 87396 -- Columns 36


Missing Values
No Missing Values found


Datatypes & Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87396 entries, 0 to 87395
Data columns (total 36 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  object
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87396 non-null  float64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  object
 13  country                         87396 non-null  object
 14  market_segment                  87396 non-null  object
 15  distribution_channel            87396 non-null  object
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  object
 20  assigned_room_type              87396 non-null  object
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  object
 23  agent                           87396 non-null  float64
 24  company                         87396 non-null  float64
 25  days_in_waiting_list            87396 non-null  int64
 26  customer_type                   87396 non-null  object
 27  adr                             87396 non-null  float64
 28  required_car_parking_spaces     87396 non-null  int64
 29  total_of_special_requests       87396 non-null  int64
 30  reservation_status              87396 non-null  object
 31  reservation_status_date         87396 non-null  object
 32  lead_time_group                 87396 non-null  object
 33  total_length_of_stay            87396 non-null  int64
 34  booking_value                   87396 non-null  float64
 35  arrival_date                    87396 non-null  object
dtypes: float64(5), int64(17), object(14)
memory usage: 24.0+ MB


Header & First Rows

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_group,total_length_of_stay,booking_value,arrival_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,180+ Days,0,0.0,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,180+ Days,0,0.0,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,0-7 Days,1,75.0,2015-07-01
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,8-14 Days,1,75.0,2015-07-01
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,8-14 Days,2,196.0,2015-07-01

In [6]:
# Check the datasest with duplicates with function
data_inspection(df_with_dup, 'Dataset with Duplicates')

============================================================
Dataset inspection for: Dataset with Duplicates
============================================================
Dataset Shape:
Rows: 119390 -- Columns 36


Missing Values
No Missing Values found


Datatypes & Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         119390 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           119390 non-null  float64
 24  company                         119390 non-null  float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  lead_time_group                 119390 non-null  object
 33  total_length_of_stay            119390 non-null  int64
 34  booking_value                   119390 non-null  float64
 35  arrival_date                    119390 non-null  object
dtypes: float64(5), int64(17), object(14)
memory usage: 32.8+ MB


Header & First Rows

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_group,total_length_of_stay,booking_value,arrival_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,180+ Days,0,0.0,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,180+ Days,0,0.0,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,0-7 Days,1,75.0,2015-07-01
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,8-14 Days,1,75.0,2015-07-01
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,8-14 Days,2,196.0,2015-07-01

In [7]:
# Implement function to calculate the total number of pax by accumulate adults + children + babies
def calculate_total_pax(df):
    """
    Summarise the total number of pax by accumulate column adults + children + babies
    """
    df['total_pax'] = df['adults'] + df['children'] + df['babies']
    df['total_pax'] = df['total_pax'].astype(int)
    return df

In [8]:
# Call funtion to calculate for both datasets
df_no_dup = calculate_total_pax(df_no_dup)
df_with_dup = calculate_total_pax(df_with_dup)

In [9]:
# Implement function to drop the adr outliers of minus and > 5000$
def remove_adr_outliers(df):
    """
    Remove the extreme outliers in the dataset with minus adr and adr over 5000
    """
    df = df[(df['adr'] >= 0) & (df['adr'] < 5000)].copy()
    return df

In [10]:
# Call function for both datasets to remove the extreme outliers
df_no_dup = remove_adr_outliers(df_no_dup)
df_with_dup = remove_adr_outliers(df_with_dup)

In [ ]:
# Implement function to check for changes between reserved room type and assigned room type
def check_roomtype_changes(df):
    """
    Check for changes between reserved room type and assigned room type
    """
    df['room_type_changes'] = (df['reserved_room_type'] != df['assigned_room_type'] ).astype(int)
    return df

In [ ]:
# Call function for roomtype changes
df_no_dup = check_roomtype_changes(df_no_dup)
df_with_dup = check_roomtype_changes(df_with_dup)

In [14]:
# Implement function to change agent and company into binary
def create_agent_company_binary(df):
    """
    Create new column has agent and has company and convert the numbers into binary
    """
    df['has_agent'] = (df['agent'] != 0).astype(int)
    df['has_company'] = (df['company'] != 0).astype(int)
    df = df.drop(columns=['company', 'agent'])
    return df

In [15]:
# Call function to change agent and company
df_no_dup = create_agent_company_binary(df_no_dup)
df_with_dup = create_agent_company_binary(df_with_dup)

In [21]:
# Implement function to seperate the countries into domestic, european and international
def create_country_regions(df):
    """
    Changes the countries into three main categories: domestic for portugal, european for all european countries and international for all other countries
    """
    europe_codes = [
        'GBR', 'FRA', 'ESP', 'DEU', 'ITA', 'IRL', 'BEL', 'NLD', 
        'CHE', 'AUT', 'SWE', 'POL', 'ISR', 'NOR']
    
    df['country_region'] = 'International'
    df.loc[df['country'].isin(europe_codes), 'country_region'] = 'Europe'
    df.loc[df['country'] == 'PRT', 'country_region'] = 'Domestic'

    df = pd.get_dummies(df, columns=['country_region'], dtype=int)

    df = df.drop(columns=['country'])
    return df

In [22]:
# Call function to seperate the countries into regions
df_no_dup = create_country_regions(df_no_dup)
df_with_dup = create_country_regions(df_with_dup)

In [ ]:
# Implement function to encode object columns with pd.get_dummies
def encode_categorial_cols(df):
    """
    Encode the remaining object (text) columns into binary features with One-Hot-Encode
    """
    columns_to_encode = ['hotel', 'meal', 'market_segment', 'distribution_channel', 'deposit_type', 'customer_type']
    df = pd.get_dummies(df, columns=columns_to_encode, dtype=int)
    return df

In [24]:
# Call function to encode
df_no_dup = encode_categorial_cols(df_no_dup)
df_with_dup = encode_categorial_cols(df_with_dup)