# Hotel Booking Demand Analysis
## Machine Learning
* **Goal:** Predict Booking Cancellations with two datasats (Dataset Comparison)

In [34]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from xgboost import XGBClassifier

In [35]:
# Import datasets with try/except

file_with_dup = 'hotel_booking_with_dup_ml.csv'
file_no_dup = 'hotel_booking_no_dup_ml.csv'

# Load dataset with duplicates
try:
    df_with_dup = pd.read_csv(file_with_dup)
    print(f'{file_with_dup} loaded successfully')
except FileNotFoundError:
    print(f'File not found - check {df_with_dup}')

# Load dataset without duplicates
try:
    df_no_dup = pd.read_csv(file_no_dup)
    print(f'{file_no_dup} loaded successfully')
except FileNotFoundError:
    print(f'File not found - check {df_no_dup}')

hotel_booking_with_dup_ml.csv loaded successfully
hotel_booking_no_dup_ml.csv loaded successfully

In [ ]:
# Implement function to check the head of both datasets

def inspection_head(df, name):
    print(f'Dataset: {name}')
    print(f'Rows: {df.shape[0]} -- Columns: {df.shape[1]}')
    display(df.head())
    return df

In [ ]:
df_with_dup = inspection_head(df_with_dup, 'with Duplicates')
df_no_dup = inspection_head(df_no_dup, 'no Duplicates')

Dataset: with Duplicates
Rohhhhws: 119388 -- Columns: 54

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,2015,27,1,0,0,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,737,2015,27,1,0,0,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,7,2015,27,1,0,1,1,0.0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,13,2015,27,1,0,1,1,0.0,0,...,0,0,0,1,0,0,0,0,1,0
4,0,14,2015,27,1,0,2,2,0.0,0,...,0,1,0,1,0,0,0,0,1,0

Dataset: no Duplicates
Rohhhhws: 87394 -- Columns: 54

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,2015,27,1,0,0,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,737,2015,27,1,0,0,2,0.0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,7,2015,27,1,0,1,1,0.0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,13,2015,27,1,0,1,1,0.0,0,...,0,0,0,1,0,0,0,0,1,0
4,0,14,2015,27,1,0,2,2,0.0,0,...,0,1,0,1,0,0,0,0,1,0